allowBuilds:
  esbuild: false
  vue-demi: false
minimumReleaseAgeExclude:
  - '@devframes/agentic@1.0.0'
  - devframe@1.0.0
  - '@devframes/hub-ui@1.0.0'
  - '@devframes/hub@1.0.0'
  - '@devframes/json-render-ui@1.0.0'
  - '@devframes/json-render@1.0.0'
  - '@devframes/plugin-inspect@1.0.0'
  - '@devframes/plugin-messages@1.0.0'
  - '@devframes/plugin-terminals@1.0.0'
  - '@devframes/service-open@1.0.0'
  - '@devframes/vite@1.0.0'
  - '@pinia/colada-devtools@2.0.0'
  - '@pinia/colada@1.4.5'
  - '@vitejs/devtools-kit@0.7.5'
  - '@vitejs/devtools-oxc@0.7.5'
  - '@vitejs/devtools-rolldown@0.7.5'
  - '@vitejs/devtools-vite@0.7.5'
  - '@vitejs/devtools-vitest@0.7.5'
  - '@vitejs/devtools@0.7.5'
